name: Run Java Class

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  run-java-class:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean package --file Firebase-Remote/pom.xml
      - name: Store artifact
        run: |
          if [ ! -d "artifacts" ]; then
            mkdir artifacts
          fi
            cp target/firebase-0.0.1-SNAPSHOT.jar artifacts/
      - name: Commit and push artifact
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git pull origin main  # Pull the latest changes from remote main branch
          git add artifacts/
          git commit -m "Add built artifact"
          git push origin HEAD:refs/heads/main



      - name: Run Java Class
        run: java -cp artifacts/firebase-0.0.1-SNAPSHOT.jar com.example.Main  

      # - name: Compile Java Class
      #   run: javac Firebase-Remote/src/main/java/com/example/Main.java  

      # - name: Run Java Class
      #   run: java -cp . com.example.Main  
      - name: Print Success
        run: 
          echo "Published successfully..."
