name: Run Java Class

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  run-java-class:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Compile Java Class
        run: javac ./com/titan/Main.java  

      # - name: Run Java Class
      #   run: java -cp . com.example.Main  
      - name: Print Success
        run: 
          echo "Published successfully..."
