name: Remote Publish

on:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can specify the version you need

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Identify Changed Files
        run: |
          changed_files=$(git log -n 1 --stat --name-status --format= -- R_D_Team)
          echo "::set-output name=changed_files::$changed_files"
       
      

      - name: Copy Changed Files
        run: |
          changed_files="${{ steps.identify.outputs.changed_files }}"
          mkdir config_changes
          for file in $changed_files; do
            cp "$file" "config_changes/"
          done
      - name: Publish Remote Config
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd config_changes
          # Authenticate with Firebase using the $FIREBASE_TOKEN secret
          echo $FIREBASE_TOKEN | firebase login:ci
          # Publish configuration changes
          firebase deploy --only remoteconfig 
